mysiteF22/myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [path(r'', views.index, name='index'),
               path(r'about/', views.about, name='about'),
               path(r'<int:cat_no>', views.detail, name='detail'),
               path(r'products/', views.products, name='products'),
               path(r'product/<int:prod_id>', views.product_detail, name='product_detail'),
               path(r'placeorder/', views.place_order, name='place_order'),
               path(r'login/', views.user_login, name='login'),
               path(r'logout/', views.user_logout, name='logout'),
               path(r'myorders/', views.myorders, name='orders'),
               path(r'register/', views.user_register, name='register')
               ]

mysiteF22/mysiteF22/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
    path(r'password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path(r'password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(r'reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path(r'reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

mysiteF22/myapp/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
import datetime
from django.contrib.auth.models import User
from django.contrib import admin
from django.utils import timezone


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    warehouse = models.CharField(max_length=200, null=True)

    # Added (null = True) so that it is possible to add
    # the warehouse field in the category because it was throwing an error

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=100, validators=[MinValueValidator(1), MaxValueValidator(999)])
    available = models.BooleanField(default=True)
    description = models.TextField(null=True, blank=True)
    interested = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.name

    def refill(self):
        self.stock += 100



class Client(User):
    PROVINCE_CHOICES = [('AB', 'Alberta'), ('MB', 'Manitoba'), ('ON', 'Ontario'), ('QC', 'Quebec'), ]
    company = models.CharField(max_length=50, null=True, blank=True)
    shipping_address = models.CharField(max_length=300, null=True, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, choices=PROVINCE_CHOICES, default='ON')
    interested_in = models.ManyToManyField(Category)
    image = models.ImageField(upload_to='images', null=True, blank=True)

    def __str__(self):
        return self.username


class Order(models.Model):
    ORDERS = [(0, 'Order Cancelled'), (1, 'Order Placed'), (2, 'OrderShipped'), (3, 'Order Delivered')]
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    num_units = models.PositiveIntegerField()
    order_status = models.IntegerField(choices=ORDERS, default=1)
    status_date = models.DateField()

    def __str__(self):
        return self.client.first_name

    def total_cost(self):
        return self.num_units * self.product.price

mysiteF22/myapp/forms.py
from django import forms
from myapp.models import Order, Client


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['client', 'product', 'num_units']
        widgets = {'client': forms.RadioSelect()}
        labels = {'client': 'Client Name', 'num_units': 'Quantity'}


class InterestForm(forms.Form):
    INTEREST = [(1, "Yes"), (0, "No")]
    interested = forms.ChoiceField(choices=INTEREST, widget=forms.RadioSelect())
    quantity = forms.IntegerField(initial=1, min_value=1, max_value=99999999)
    comments = forms.CharField(widget=forms.Textarea, label="Additional Comments", required=False)


class RegisterForm(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'company', 'shipping_address',
                  'city', 'province', 'interested_in', 'image']
        widgets = {'interest_in': forms.CheckboxSelectMultiple()}
        labels = {'first_name': 'First name', 'last_name': 'Last name', 'shipping_address': 'Shipping address',
                  'interested_in': 'Interested in', 'image': 'Profile picture'}

# class User(forms.Form):
#     username = forms.CharField(label="Username", max_length=30)
#     password = forms.CharField(widget=forms.PasswordInput(),label="Password")

mysiteF22/myapp/views.py
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from .forms import OrderForm, InterestForm, RegisterForm
from .models import Category, Product, Client, Order
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test


# Create your views here.

def index(request):
    cat_list = Category.objects.all().order_by('id')[:10]
    return render(request, 'myapp/index.html', {'cat_list': cat_list})


def about(request):
    response = render(request, 'myapp/about.html')
    x = request.COOKIES.get('about_visits')
    if x is None:
        x = 1
    else:
        x = int(x)
        x += 1
    response.set_cookie(key='about_visits', value=x, max_age=30)
    return response


def detail(request, cat_no):
    category = get_object_or_404(Category, pk=cat_no)
    prod_list = Product.objects.filter(category__id=cat_no)
    return render(request, 'myapp/detail.html', {'category': category, 'prod_list': prod_list})


def products(request):
    prod_list = Product.objects.all().order_by('id')[:10]
    return render(request, 'myapp/products.html', {'prod_list': prod_list})


def place_order(request):
    msg = ''
    prod_list = Product.objects.all()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if order.num_units <= order.product.stock:
                order.order_status = 1
                order.status_date = datetime.date.today()
                order.save()
                product = prod_list.get(name=order.product.name)
                product.stock -= order.num_units
                product.save()
                msg = 'Your order has been placed successfully.'
            else:
                msg = 'We do not have sufficient stock to fill your order.'
            return render(request, 'myapp/order_response.html', {'msg': msg})
    else:
        form = OrderForm()
    return render(request, 'myapp/placeorder.html', {'form': form, 'msg': msg, 'prod_list': prod_list})


def product_detail(request, prod_id):
    product = get_object_or_404(Product, pk=prod_id)
    msg = ""
    if request.method == 'POST':
        form = InterestForm(request.POST)
        if form.is_valid():
            product.interested += int(form.cleaned_data['interested'])
            product.save()
            return redirect('/myapp/')
    else:
        if product.available:
            msg = 'Product is currently available!!! :)'
        else:
            msg = 'Product is not available!!! :('
    form = InterestForm()
    return render(request, 'myapp/productdetail.html', {'product': product, 'msg': msg, 'form': form})


def user_register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'myapp/login.html')
        else:
            return HttpResponse('Registration was unsuccessful')
    else:
        form = RegisterForm()
        return render(request, 'myapp/register.html', {'form': form})


def user_login(request):
    last_url = request.META.get('HTTP_REFERER')
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                current_datetime = datetime.datetime.now().strftime("%m/%d/%Y, %H:%M:%S")
                request.session['last_login'] = current_datetime
                request.session.set_expiry(3600)
                if last_url == "http://localhost:8000/myapp/myorders/":
                    return HttpResponseRedirect(reverse('myapp:orders'))
                else:
                    return HttpResponseRedirect(reverse('myapp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')


def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('myapp:index'))


def myorders(request):
    if request.user.is_authenticated:
        try:
            client = Client.objects.get(username=request.user.username)
        except ObjectDoesNotExist:
            return HttpResponse('You are not a registered client!')
        if client:
            order_list = Order.objects.filter(client=client)
            if order_list:
                msg = 'Orders placed by ' + client.first_name + ' ' + client.last_name
            else:
                msg = 'No order placed by ' + client.first_name + ' ' + client.last_name
            return render(request, 'myapp/myorders.html', {'orders': order_list, 'msg': msg})
    else:
        return render(request, 'myapp/login.html')

mysiteF22/myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}
{% block title %}
    About the app
{% endblock %}
{% block body_block %}
    <p>This is an Online Store APP.</p>
    {% if request.COOKIES.about_visits is not None %}
        <p>Number of times the ABOUT page has been visited so far - {{ request.COOKIES.about_visits }}</p>
    {% endif %}
{% endblock %}

mysiteF22/myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <title>Online Store APP - {% block title %}Welcome!{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href = "{% url 'myapp:index' %}">Main Page</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/myapp/products/">Available products</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/myapp/about/">About</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    {% block login_urls %}
                    {% if request.user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <b>Hello {{ request.user.first_name }}</b>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'myapp:orders' %}">My orders</a>
                            <a class="dropdown-item" href="/myapp/logout/">Logout</a>
                        </div>
                    {% else %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle='dropdown' aria-haspopup="true" aria-expanded="false">
                            <b>Hello User</b>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'myapp:login' %}">Login</a>
                            <a class="dropdown-item" href="{% url 'myapp:register' %}">Register</a>
                        </div>
                    {% endif %}
                    {% endblock %}
                </li>
            </ul>
        </div>
    </nav>
    <div>
        {% block body_block %}*** {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    </div>
</body>
</body>
</html>

mysiteF22/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
{% block title %}
    {{ category.name }} details
{% endblock %}
{% block body_block %}
    {% if category %}
    <h4>Location of Category {{ category.name }} is {{ category.warehouse }}</h4>
    {% endif %}
    {% if prod_list %}
    <ol>
     {% for product in prod_list %}
    <li style="color: green"> {{ product.name}} </li>
     {% endfor %}
    </ol>
    {% else %}
    <strong style="color: red">There are no products for this category!</strong>
    {% endif %}
{% endblock %}

mysiteF22/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if cat_list %}
    <h2>List of Categories</h2>
        <div style="margin-right: 800px" class="list-group">
            {% for cat in cat_list %}
            <a class="list-group-item list-group-item-action" href="{%  url 'myapp:detail' cat.id %}">{{ cat.name }}</a>
            {% endfor %}
        </div>
    {% else %}
        <strong>There are no available categories!</strong>
    {% endif %}
    {% if request.session.last_login %}
        <p>Last login - {{ request.session.last_login }}</p>
    {% else %}
        <p>Your last login was more than one hour ago</p>
    {% endif %}
{% endblock %}

mysiteF22/myapp/templates/myapp/login.html
{% extends 'myapp/base.html' %}
{% block title %}
    Login
{% endblock %}
{% block myhdg %}
{% endblock %}
{% block body_block %}
    <div class="container-fluid">
        <form action="/myapp/login/" method="post">
            {% csrf_token %}
            <div class="form-row">
                <div class="form-group col-md-4 mb-0 form-outline form-white mb-4">
                    <label class="form-label" for="username">Username</label>
                    <input class="form-control form-control-lg" type="text" id="username" name="username">
                </div>
            </div>
            <div class="form-row">
                <div class="form-group col-md-4 mb-0 form-outline form-white mb-4">
                    <label class="form-label" for="password">Password</label>
                    <input class="form-control form-control-lg" type="password" id="password" name="password">
                </div>
            </div>
            <button type="submit" class="btn btn-success">Login</button>
        </form>
    </div>
{% endblock %}
{% block login_urls %}
    {% if request.user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <b>Hello {{ request.user.first_name }}</b>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'myapp:orders' %}">My orders</a>
                            <a class="dropdown-item" href="/myapp/logout/">Logout</a>
                        </div>
                    {% else %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle='dropdown' aria-haspopup="true" aria-expanded="false">
                            <b>Hello User</b>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'myapp:register' %}">Register</a>
                            <a class="dropdown-item" href="{% url 'password_reset' %}">Forgot Password</a>
                        </div>
                    {% endif %}
{% endblock %}

mysiteF22/myapp/templates/myapp/myorders.html
{% extends 'myapp/base.html' %}
{% block title %}
    Orders
{% endblock %}
{% block body_block %}
    <h3>{{ msg }}</h3>
    <ol>
    {% for order in orders %}
        <li><b>{{ order.product.name }}</b></li>
        <ul>
            <li>Quantity - {{ order.num_units }}</li>
            <li>Status - {{ order.order_status }}</li>
            <li>Ordered on - {{ order.status_date }}</li>
            <li>Total cost - {{ order.total_cost }}</li>
        </ul>
    {% endfor %}
    </ol>
{% endblock %}

mysiteF22/myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    <p>{{ msg }}</p>
{% endblock %}

mysiteF22/myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if prod_list %}
    <h2>List of Products and their prices</h2>
    <ol>
     {% for prod in prod_list %}
             <li>{{ prod.name }} - CAD {{ prod.price }} - Quantity {{ prod.stock }}</li>
     {% endfor %}
    </ol>
    {% endif %}

    <form action="/myapp/placeorder/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Place Order"/></form>

{% endblock %}

mysiteF22/myapp/templates/myapp/productdetail.html
{% extends 'myapp/base.html' %}
{% block title %}
    {{ product.name }} details
{% endblock %}
{% block body_block %}
    {% if product %}
    <h2>{{ product.name }}</h2>
    {% endif %}
    <h4>{{ product.interested }} number of people are interested in this product </h4>
    <p style="color: green">Price - {{ product.price }}</p>
    <br>
    <br>
    {{ msg }}
    <form action="/myapp/product/{{ product.id }}" method="post">
    {% csrf_token %}
    <table>{{ form.as_table }}</table>
    <input type="submit" value="Submit" class="btn btn-primary" /></form>
{% endblock %}

mysiteF22/myapp/templates/myapp/products.html
{% extends 'myapp/base.html' %}
{% block body_block %}
    {% if prod_list %}
    <h2>List of Products that are available</h2>
    <div style="margin-right: 800px" class="list-group">
        {% for prod in prod_list %}
         {% if prod.available %}
             <a class="list-group-item list-group-item-action" href="{%  url 'myapp:product_detail' prod.id %}">{{ prod.name }}</a>
         {% endif %}
     {% endfor %}
    </div>
        <br>
    <button class="btn btn-primary"><a style="color: white" href="{% url 'myapp:place_order' %}">Place an order</a></button>
    {% endif %}
{% endblock %}

mysiteF22/myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    Register
{% endblock %}
{% block myhdg %}
    Registration Form
{% endblock %}
{% block body_block %}
    <form action="/myapp/register/" method="post">
    <div class="container-fluid">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.username|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
                {{ form.password|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.first_name|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
                {{ form.last_name|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.city|as_crispy_field }}
                {{ form.province|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
                {{ form.shipping_address|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
                {{ form.email|as_crispy_field }}
            </div>
            <div class="form-group col-md-4 mb-0">
                {{ form.company|as_crispy_field }}
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-4 mb-0">
              {{ form.interested_in|as_crispy_field }}
              {{ form.image|as_crispy_field }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </div>
    </form>
{% endblock %}
{% block login_urls %}
    {% if request.user.is_authenticated %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <b>Hello {{ request.user.first_name }}</b>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'myapp:orders' %}">Check my orders</a>
                            <a class="dropdown-item" href="/myapp/logout/">Logout</a>
                        </div>
                    {% else %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle='dropdown' aria-haspopup="true" aria-expanded="false">
                            <b>Hello User</b>
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'myapp:login' %}">Login</a>
                        </div>
                    {% endif %}
{% endblock %}